### ISSUE TITLE
update to emoji 5.0

### ISSUE THREAD

**Issue by qwertygc** [mozilla/twemoji-colr#18]
hey !
We have new emoji with emojis 5.0. it's possible to update ?
Regards

**Comment by timdream** [comment]
Hi,

Please take a look at https://bugzilla.mozilla.org/show_bug.cgi?id=1358240
Basically, we cannot upgrade this to a non-free license. We would need to move away from EmojiOne or ask them to re-release newer versions (perhaps not the latest) with the free license.

Maintaining this project also takes a bit of labor, and even more labor if we make a switch. Given this is a feature only exposed to a fraction of Firefox users (and it will get smaller as people upgrade to newer Windows), solutions make sense technically might not make sense economically. Thank you for your understanding.

**Comment by TheEssemCraft** [comment]
@timdream Maybe we could make one for [Twemoji](https://github.com/twitter/twemoji)? It's under a free software license.

**Comment by TheEssemCraft** [comment]
So I made a few changes to the repo to implement Twemoji, can anyone try to build/test it? I can't do it myself since I don't have Linux/macOS, and I am also on a trip somewhere: https://github.com/TheEssemCraft/emojione-colr

**Comment by timdream** [comment]
If your Windows machine is relatively modern, you can setup a virtual
machine with Debian to test this out.
-- 
(Apologies — sent from mobile)

**Comment by TheEssemCraft** [comment]
@timdream The problem is that I'm using a work laptop that doesn't let me install software. So I can't do that.

**Comment by TheEssemCraft** [comment]
I tried to do a test build using Travis CI, but it failed. Here's the log: https://gist.github.com/TheEssemCraft/49728eb7e00339a060e0a8ec939da246

**Comment by timdream** [comment]
@TheEssemCraft I don't really know what happen with that log. Preferably you should use a VM like https://ide.c9.io/ to actually develop in a compatible environment, or spend a little money on hourly VPS.

**Comment by TheEssemCraft** [comment]
@timdream Updated the log for clarity. Also, I looked at Cloud9, and apparently the free account needs your credit card?! I don't have a credit card, and I don't know of anyone that will let me use theirs.

**Comment by TheEssemCraft** [comment]
When I try to build it, it throws an error on line 387 of layerize.js. Here's the log when I run `make`:

```
node layerize.js twe-svg.zip overrides extras build Twemoji\ Mozilla
events.js:136
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'forEach' of undefined
    at /home/travis/build/TheEssemCraft/twemoji-colr/layerize.js:387:29
    at Array.forEach (<anonymous>)
    at addToPaths (/home/travis/build/TheEssemCraft/twemoji-colr/layerize.js:385:19)
    at /home/travis/build/TheEssemCraft/twemoji-colr/layerize.js:525:9
    at Parser.<anonymous> (/home/travis/build/TheEssemCraft/twemoji-colr/node_modules/xml2js/lib/parser.js:303:18)
    at Parser.emit (events.js:159:13)
    at SAXParser.onclosetag (/home/travis/build/TheEssemCraft/twemoji-colr/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/home/travis/build/TheEssemCraft/twemoji-colr/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/home/travis/build/TheEssemCraft/twemoji-colr/node_modules/sax/lib/sax.js:620:3)
    at closeTag (/home/travis/build/TheEssemCraft/twemoji-colr/node_modules/sax/lib/sax.js:861:5)
make: *** [build/codepoints.js] Error 1
```

**Comment by TheEssemCraft** [comment]
Okay, so I looked some more into how Twemoji formats its SVGs, and here's some of what I found: 
- There's a metadata tag in every SVG
- There's also a defs tag in every SVG, even when unneeded
- Almost everything is organized into groups
- Colors are stored using CSS instead of the fill tag
- Groups aren't sorted by colors
- Pretty much everything has an ID
