### ISSUE TITLE
Switch to Emoji Two

### ISSUE THREAD

**Issue by jbicha** [mozilla/twemoji-colr#19]
I believe you're aware that the latest versions of Emoji One are no longer available under a [license](https://www.emojione.com/licenses) that allows free modification and distribution.

Please switch to Emoji Two https://github.com/EmojiTwo/emojitwo
It doesn't have an official release yet, but I think a git snapshot would work.

See also https://bugzilla.mozilla.org/1358240

**Comment by TheEssemCraft** [comment]
I don't think that EmojiTwo is sufficient right now as there are very few changes between it and EmojiOne. However, while there isn't an EmojiTwo version that I know of, I am working on a version that uses Twemoji: https://github.com/TheEssemCraft/twemoji-colr

**Comment by timdream** [comment]
@TheEssemCraft pushed his branch upstream; we should go with Twemoji.
