### ISSUE TITLE
[Test suite] ReferenceError: options is not defined

### ISSUE THREAD

**Issue by TheEssemCraft** [mozilla/twemoji-colr#21]
With newer versions of `resemblejs`, when you try to run the test suite, it throws this error:
```
ReferenceError: options is not defined
compare@http://twemoji-colr.herokuapp.com/node_modules/resemblejs/resemble.js:636:5
wrapper@http://twemoji-colr.herokuapp.com/node_modules/resemblejs/resemble.js:779:7
onComplete@http://twemoji-colr.herokuapp.com/node_modules/resemblejs/resemble.js:782:6
imageCompare/</<@http://twemoji-colr.herokuapp.com/index.js:314:11
imageCompare/<@http://twemoji-colr.herokuapp.com/index.js:312:16
```
It seems this has to do with the new `resemble.compare` API in version 2.6.0. We might need to rewrite the comparison script to work with the new version.

**Comment by TheEssemCraft** [comment]
Never mind, `resemblejs` version 2.7.1 fixed the issue... for now. Whenever the code is run, it gives this warning in the console:

```
warning resemble.outputSettings mutates global state, and will be removed in 3.0.0
```

So it seems that the current code will work until version 3.0.0. I will reopen this issue when that version is released.

**Comment by TheEssemCraft** [comment]
We can replace `outputSettings` with this:

```
var options = {
    output: {
        errorColor: {
            red: 255,
            green: 0,
            blue: 255
        },
        largeImageThreshold: 0,
        outputDiff: true
    }
};
```
This method is mentioned in [the documentation](https://github.com/Huddle/Resemble.js#single-callback-api). However, it seems that they want us to use `resemble.compare` instead.

**Comment by timdream** [comment]
I assume you don't have issue with this anymore?

**Comment by TheEssemCraft** [comment]
@timdream Not really. However, this issue might pop up again in the future.
