### ISSUE TITLE
UN flag doesn't match up to the source SVG

### ISSUE THREAD

**Issue by TheEssemCraft** [mozilla/twemoji-colr#28]
I've found through testing that the UN flag emoji (U+1F1FA, U+1F1F3) is slightly messed up in the middle, as you can see here:
![UN flag](https://bug1358240.bmoattachments.org/attachment.cgi?id=8963647)
The continents are larger and overlap each other. It seems to happen after the layerize script, as each layer SVG is correct. Maybe it has to do with grunt-webfont? 🤔

**Comment by TheEssemCraft** [comment]
I investigated a bit more and found that the size of the SVGs might be to blame, as grunt-webfont seems to work better with larger SVGs, especially 512px ones. Relevant bug: https://github.com/sapegin/grunt-webfont/issues/321

**Comment by KwanEsq** [comment]
Would it be worth adding an override SVG for this as a workaround?  After chopping up the paths a bit with Inkscape (then trimming the markup back down again) I have an SVG that when placed in overrides produces a decent rendering.

**Comment by timdream** [comment]
That could be a viable solution.

**Comment by KwanEsq** [comment]
I've finally pushed my mentioned override to https://github.com/KwanEsq/twemoji-colr/commit/4f3c9bb89b68cc0da6eb2575cea2393da862f4b8
It's possible it could be simplified a bit, but it does the job.

**Comment by KwanEsq** [comment]
So to document the steps for creating the override file:

1) Copy twemoji/2/svg/1f1fa-1f1f3.svg to twemoji-colr/overrides/1f1fa-1f1f3.svg
1) Open twemoji-colr/overrides/1f1fa-1f1f3.svg in Inkscape
1) Select the path with the landmasses in (7th of the 9 paths in the group)
1) In the "Path" menu select "Break Apart"
1) Several of the ocean sections are now solid white
1) Select one of the new paths making up a white ocean section
1) Shift-click every re-coloured ocean section, so they are all selected at once
1) Open twemoji/2/svg/1f1fa-1f1f3.svg in Inkscape
1) Flick between the modified and second copy to compare and not miss any small bits
1) In the "Fill and Stroke" > "Fill" panel click on "Flat colour"
1) Use the colour picker to set the background blue as the fill colour
1) Double check you didn't miss any small bits
1) In the "Object" menu select "Group"
1) "File" > "Save As..."
1) Choose "Optimised SVG" as the output format
1) Tick the following options:
    1) Options
        1) Shorten colour values
        1) Convert CSS attributes to XML attributes
        1) Collapse groups
        1) Create groups for similar attributes
        1) Work around renderer bugs
    1) SVG Output
        1) Remove the XML declaration
        1) Remove metadata
        1) Remove comments
    1) IDs
        1) Remove unused IDs
1) Save
1) Optional: open the override SVG and remove the version attribute from the root svg element
