### ISSUE TITLE
Ubuntu Getting Started instructions miss out python-fontforge package

### ISSUE THREAD

**Issue by KwanEsq** [mozilla/twemoji-colr#35]
Trying to follow the current instructions results in
```python
Traceback (most recent call last):
  File "fixDirection.py", line 1, in <module>
    import fontforge
ImportError: No module named fontforge
```
after `make`.
I had to (discover and) install the python-fontforge package from apt to be able to build successfully.

**Comment by RMWinslow** [comment]
I had the same `ImportError: No module named fontforge` on MacOS.    
As a workaround, I changed `PYTHON     ?= python3` in the makefile to `PYTHON     ?= fontforge -script`

When homebrew installs fontforge, it's supposed to both:
- embed python into fontforge and 
- install fontforge as a python extension
For my installation, the latter step failed. Looking at the issues on the fontforge project, I found several people with the same problem on Mac, but no simple fix. The easiest workaround is to instead [call the version of python embedded into fontforge](https://fontforge.org/docs/scripting/scripting.html), which can be done using `fontforge -script foo.py {arguments}`

I think this issue originates with either fontforge or homebrew, so it’s not worth trying to figure out here. But I thought this might be useful information for  anyone else who runs into the same problem when trying to build this font.
