### ISSUE TITLE
Should we care that some of the Twemoji filenames don't match their actual sequence

### ISSUE THREAD

**Issue by KwanEsq** [mozilla/twemoji-colr#45]
See twitter/twemoji#272.
They are missing FE0F: VS16.
This affects keycap sequences and the ["eye in speech bubble"](https://emojipedia.org/eye-in-speech-bubble/).
Should we give them the proper sequences during font creation? Easy enough to do during `processFile` in layerize.js.
Though for some reason they still seem able to be used for the actual sequence in pages (but the keycaps require explicit `font-family: "Twemoji Mozilla";` for some reason).

cc @jfkthame

**Comment by jfkthame** [comment]
Yes, I think we should fix these to match the sequences that are expected to be used in content.
