### ISSUE TITLE
Provide updated releases on GitHub

### ISSUE THREAD

**Issue by wolfbeast** [mozilla/twemoji-colr#49]
Please provide updated binary releases on GitHub. They are still stuck at 0.3.2, and e.g. https://hg.mozilla.org/mozilla-central/rev/9bdb1897c29a indicates there is at least a 0.4.0 -- providing binary releases here will allow other projects than Firefox to follow suit.

**Comment by KwanEsq** [comment]
@jfkthame are you able to take care of this?

**Comment by jfkthame** [comment]
Created release v0.4.0.
